name: VI-CD-pipeline-to-AWS-elasticbeanstalk
env:
  EB_PACKAGE_S3_BUCKET_NAME : "marat-flask-application-packages"
  EB_APPLICATION_NAME : "myFlask"
  EB_ENVIRONMENT_NAME : "Myflask-env"
  DEPLOY_PACKAGE_NAME : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME : "eu-central-1"

on:
  workflow_dispatch:
    
jobs:
  my_ci_part:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git clone our repo
      uses: actions/checkout@v1
      
      
    - name: Create ZIP deployment package
      run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
      
      
      
