#comment
#git hub
#sdfsf
name: My-GitHubActions-Basics

on: 
  push:
    branches: 
      - master 

jobs:
  my_testing:
  
    runs-on:  ubuntu-latets
    
    steps:
    - name: Print Hello Message
      run : echo "Hello world"
    
  
  my_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Print hello mesage
      run: echo "Hello world from deploy job"
    
